---
title: "Digitizing Plant Architecture: 3D Reconstruction of Vine"
author: "DS"
date: "2019"
output:
  html_document:
    code_folding: hide
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}


# Set pre-processing code for sourcing
baseCodeFile <- "digi2table_Riesling.R"

# Estimate lines of code to source -- until 'SOURCEBREAK'
#lineN <- as.numeric(system(paste0('grep -n "SOURCEBREAK" ',baseCodeFile,' | grep -o [0-9]*.*[0-9]'),intern=TRUE))

# # function to source only n-lines
# source2 <- function(file, start, end, ...) {
#     file.lines <- scan(file, what=character(), skip=start-1, nlines=end-start+1, sep='\n')
#     file.lines.collapsed <- paste(file.lines, collapse='\n')
#     source(textConnection(file.lines.collapsed), ...)
# }
# # Source
# source2(baseCodeFile,1,lineN)


source(baseCodeFile)

# Load additonal Packages
# usePackage("data.table")
# usePackage("rgl")		
 usePackage("rglwidget")
# usePackage("stringi")
# usePackage("RColorBrewer")
 	options(rgl.useNULL = TRUE)

```



```{r}

result <- list()
for(ni in 1:length(flist)){		
       result[[ni]] <- rglwidget(x=plotRGL(flist[ni]))
}
htmltools::tagList(result)

```
